import "./globals.css";

import Menu from "./components/menu";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="mx-1 font-helvetica-neue">
        <div className="bg"></div>
        <Menu />
        {children}
      </body>
    </html>
  );
}
