name: auto-deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Production Auto-Deploy
        uses: garygrossgarten/github-action-ssh@0.7.0
        with:
          command: cd explorer && git checkout main && git pull && pm2 restart explorer
          host: ${{ secrets.PROD_HOST }}
          username: gmadmin
          privateKey: ${{ secrets.PROD_PRIVATE_KEY}}
        env:
          CI: true
