name: auto-deploy

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Production Autodeploy
        if: github.ref == 'refs/heads/main'
        uses: garygrossgarten/github-action-ssh@0.7.0
        with:
          command: cd explorer && git checkout main && git pull && pm2 restart explorer;
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          privateKey: ${{ secrets.PROD_PRIVATE_KEY}}
