name: auto-deploy

on: push

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Production Auto-Deploy
        if: github.ref == 'refs/heads/main'
        uses: garygrossgarten/github-action-ssh@v0.6.4
        with:
          command: cd explorer && git checkout main && git pull && pm2 restart explorer
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          privateKey: ${{ secrets.PROD_PRIVATE_KEY}}
